# Shared configuration used by all agents
email:
  smtp_server: "smtp.mail.me.com"
  smtp_port: 587
  username: "" # Set via EMAIL_USERNAME env var
  password: "" # Set via EMAIL_PASSWORD env var
  from_email: ""
  to_email: ""

monitoring:
  health_port: 8080

# YouTube Curator Agent Configuration
youtube_curator:
  youtube:
    client_id: "" # Set via GOOGLE_CLIENT_ID env var
    client_secret: "" # Set via GOOGLE_CLIENT_SECRET env var
    token_file: "data/youtube_token.json"
    token_refresh_minutes: 30 # Refresh token every 30 minutes in background

  ai:
    gemini_api_key: "" # Set via GEMINI_API_KEY env var
    model: "gemini-2.5-flash"

  video:
    short_minutes: 1
    long_minutes: 60

  guidelines:
    criteria:
      - "Educational content about programming, technology, or software development"
      - "High-quality tutorials or explanations of complex topics"
      - "Industry insights from experienced professionals"
      - "New technology announcements or reviews"
      - "Content that would help with professional development"
      - "Avoid clickbait or overly promotional content"
      - "Prefer content from established creators with good reputation"

  schedule: "0 0 9 * * *" # Daily at 9 AM

# Drone Weather Agent Configuration
drone_weather:
  # User's home location (configurable for any US location)
  home_latitude: 37.7749
  home_longitude: -122.4194
  home_name: "San Francisco Bay Area"

  # TFR search area around home location
  search_radius_miles: 25

  # Weather thresholds (SI units)
  max_wind_speed_kmh: 25    # 25 km/h wind speed limit
  min_visibility_km: 5      # 5 km visibility requirement
  max_precipitation_mm: 0   # No precipitation allowed
  min_temp_c: 4.4          # 4.4°C minimum temperature
  max_temp_c: 35.0         # 35°C maximum temperature

  # APIs (defaults provided)
  weather_url: "https://api.open-meteo.com/v1/forecast"
  tfr_url: "https://tfr.faa.gov/tfr2/list.html"

  schedule: "0 0 9 * * *" # Daily at 9 AM
